### ISSUE TITLE
feat:UIの改善

### ISSUE THREAD

**Issue by kiharu3112** [poporonnet/kanicon-writer-front#13]
マイコンボードの選択画面を小さくしてシリアルモニタをもっと上に表示する

**Comment by speak-mentaiko** [comment]
ついでにシリアルモニターを読めない人間がほとんどなので、現在のステータス(例：接続待機中とか)を出してほしいかも

**Comment by kiharu3112** [comment]
あー。 @tufusa 実現可能性としてどうですか

**Comment by tufusa** [comment]
> 現在のステータス(例：接続待機中)

もうちょっと具体的にどんなステータスが欲しいか教えてくれると助かる
現状だと、ボタン類は押せるときにしか押せないのでそれがステータス代わりという意図があった

**Comment by speak-mentaiko** [comment]
ステータス例？
- 接続待機中
- 接続中
- 書き込み待機中
- 書き込み中
- 書き込み完了

書いててこれ必要か分らんくなってきた
